export const mockData = [
  {
    id: 1,
    liga_id: 1,
    sede_id: 1,
    fecha: "2023-05-15T18:00:00Z",
    estado: "finalizado",
    equipo1_id: 1,
    equipo2_id: 2,
    equipo1: {
      id: 1,
      jugador1: "Carlos Martínez",
      jugador2: "Ana López",
      nivel: "Avanzado",
    },
    equipo2: {
      id: 2,
      jugador1: "Juan Pérez",
      jugador2: "María García",
      nivel: "Avanzado",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Primera",
    },
    sede: {
      id: 1,
      nombre: "Club Deportivo Central",
      direccion: "Av. Central 123",
      pista: 3,
    },
    resultado: {
      sets: [
        { equipo1: 6, equipo2: 4 },
        { equipo1: 7, equipo2: 6 },
      ],
      ganador: 1,
    },
  },
  {
    id: 2,
    liga_id: 1,
    sede_id: 2,
    fecha: "2023-05-22T19:30:00Z",
    estado: "finalizado",
    equipo1_id: 1,
    equipo2_id: 3,
    equipo1: {
      id: 1,
      jugador1: "Carlos Martínez",
      jugador2: "Ana López",
      nivel: "Avanzado",
    },
    equipo2: {
      id: 3,
      jugador1: "Roberto Sánchez",
      jugador2: "Laura Fernández",
      nivel: "Avanzado",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Primera",
    },
    sede: {
      id: 2,
      nombre: "Club Metropolitano",
      direccion: "Calle Norte 456",
      pista: 1,
    },
    resultado: {
      sets: [
        { equipo1: 4, equipo2: 6 },
        { equipo1: 3, equipo2: 6 },
      ],
      ganador: 2,
    },
  },
  {
    id: 3,
    liga_id: 2,
    sede_id: 1,
    fecha: "2023-05-29T20:00:00Z",
    estado: "en juego",
    equipo1_id: 1,
    equipo2_id: 4,
    equipo1: {
      id: 1,
      jugador1: "Carlos Martínez",
      jugador2: "Ana López",
      nivel: "Avanzado",
    },
    equipo2: {
      id: 4,
      jugador1: "Miguel Torres",
      jugador2: "Sofía Ramírez",
      nivel: "Avanzado",
    },
    liga: {
      id: 2,
      nombre: "Torneo Regional",
      categoria: "Open",
    },
    sede: {
      id: 1,
      nombre: "Club Deportivo Central",
      direccion: "Av. Central 123",
      pista: 2,
    },
    resultado: {
      sets: [
        { equipo1: 6, equipo2: 4 },
        { equipo1: 3, equipo2: 5 },
      ],
      ganador: 1,
    },
  },
  {
    id: 4,
    liga_id: 1,
    sede_id: 3,
    fecha: "2023-06-05T18:00:00Z",
    estado: "programado",
    equipo1_id: 1,
    equipo2_id: 5,
    equipo1: {
      id: 1,
      jugador1: "Carlos Martínez",
      jugador2: "Ana López",
      nivel: "Avanzado",
    },
    equipo2: {
      id: 5,
      jugador1: "Pablo Ruiz",
      jugador2: "Elena Díaz",
      nivel: "Avanzado",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Primera",
    },
    sede: {
      id: 3,
      nombre: "Club Municipal",
      direccion: "Plaza Mayor 789",
      pista: 4,
    },
  },
  {
    id: 5,
    liga_id: 1,
    sede_id: 1,
    fecha: "2023-06-12T19:30:00Z",
    estado: "programado",
    equipo1_id: 1,
    equipo2_id: 6,
    equipo1: {
      id: 1,
      jugador1: "Carlos Martínez",
      jugador2: "Ana López",
      nivel: "Avanzado",
    },
    equipo2: {
      id: 6,
      jugador1: "Javier Moreno",
      jugador2: "Carmen Vega",
      nivel: "Avanzado",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Primera",
    },
    sede: {
      id: 1,
      nombre: "Club Deportivo Central",
      direccion: "Av. Central 123",
      pista: 1,
    },
  },
  {
    id: 6,
    liga_id: 2,
    sede_id: 2,
    fecha: "2023-05-16T18:00:00Z",
    estado: "finalizado",
    equipo1_id: 7,
    equipo2_id: 8,
    equipo1: {
      id: 7,
      jugador1: "Daniel Herrera",
      jugador2: "Lucía Ortiz",
      nivel: "Intermedio",
    },
    equipo2: {
      id: 8,
      jugador1: "Alejandro Blanco",
      jugador2: "Isabel Navarro",
      nivel: "Intermedio",
    },
    liga: {
      id: 2,
      nombre: "Torneo Regional",
      categoria: "Intermedia",
    },
    sede: {
      id: 2,
      nombre: "Club Metropolitano",
      direccion: "Calle Norte 456",
      pista: 2,
    },
    resultado: {
      sets: [
        { equipo1: 6, equipo2: 2 },
        { equipo1: 6, equipo2: 3 },
      ],
      ganador: 1,
    },
  },
  {
    id: 7,
    liga_id: 2,
    sede_id: 3,
    fecha: "2023-05-23T19:30:00Z",
    estado: "finalizado",
    equipo1_id: 7,
    equipo2_id: 9,
    equipo1: {
      id: 7,
      jugador1: "Daniel Herrera",
      jugador2: "Lucía Ortiz",
      nivel: "Intermedio",
    },
    equipo2: {
      id: 9,
      jugador1: "Fernando Castro",
      jugador2: "Raquel Jiménez",
      nivel: "Intermedio",
    },
    liga: {
      id: 2,
      nombre: "Torneo Regional",
      categoria: "Intermedia",
    },
    sede: {
      id: 3,
      nombre: "Club Municipal",
      direccion: "Plaza Mayor 789",
      pista: 3,
    },
    resultado: {
      sets: [
        { equipo1: 6, equipo2: 7 },
        { equipo1: 6, equipo2: 4 },
        { equipo1: 10, equipo2: 8 },
      ],
      ganador: 1,
    },
  },
  {
    id: 8,
    liga_id: 1,
    sede_id: 1,
    fecha: "2023-05-30T20:00:00Z",
    estado: "en juego",
    equipo1_id: 7,
    equipo2_id: 10,
    equipo1: {
      id: 7,
      jugador1: "Daniel Herrera",
      jugador2: "Lucía Ortiz",
      nivel: "Intermedio",
    },
    equipo2: {
      id: 10,
      jugador1: "Andrés Molina",
      jugador2: "Patricia Serrano",
      nivel: "Intermedio",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Segunda",
    },
    sede: {
      id: 1,
      nombre: "Club Deportivo Central",
      direccion: "Av. Central 123",
      pista: 4,
    },
    resultado: {
      sets: [
        { equipo1: 3, equipo2: 6 },
        { equipo1: 5, equipo2: 3 },
      ],
      ganador: 2,
    },
  },
  {
    id: 9,
    liga_id: 2,
    sede_id: 2,
    fecha: "2023-06-06T18:00:00Z",
    estado: "programado",
    equipo1_id: 7,
    equipo2_id: 11,
    equipo1: {
      id: 7,
      jugador1: "Daniel Herrera",
      jugador2: "Lucía Ortiz",
      nivel: "Intermedio",
    },
    equipo2: {
      id: 11,
      jugador1: "Sergio Reyes",
      jugador2: "Natalia Vargas",
      nivel: "Intermedio",
    },
    liga: {
      id: 2,
      nombre: "Torneo Regional",
      categoria: "Intermedia",
    },
    sede: {
      id: 2,
      nombre: "Club Metropolitano",
      direccion: "Calle Norte 456",
      pista: 1,
    },
  },
  {
    id: 10,
    liga_id: 1,
    sede_id: 3,
    fecha: "2023-06-13T19:30:00Z",
    estado: "programado",
    equipo1_id: 7,
    equipo2_id: 12,
    equipo1: {
      id: 7,
      jugador1: "Daniel Herrera",
      jugador2: "Lucía Ortiz",
      nivel: "Intermedio",
    },
    equipo2: {
      id: 12,
      jugador1: "Víctor Mendoza",
      jugador2: "Cristina Luna",
      nivel: "Intermedio",
    },
    liga: {
      id: 1,
      nombre: "Liga Municipal",
      categoria: "Segunda",
    },
    sede: {
      id: 3,
      nombre: "Club Municipal",
      direccion: "Plaza Mayor 789",
      pista: 2,
    },
  },
];
